feat: added functional extensions in dart packages (#4)
* feat: add build_runner and clean countries_flutter

* ci(github): update workflows and dependabot

* feat: generated fiat currency functional methods

* feat: generated natural lang functional methods

* feat: generated lang family functional methods

* feat: generated world country functional methods

* feat: generated continent functional methods

* style: added todos in pubspec for publish_to

* fix: comment out build_runner for now

* fix(github): provide relative path to pana check

* fix(github): provide any channel to flutter action

* fix(github): temporary disable pana action

* fix(github): provide dummy test for countries_flutter

* fix(github): provide dummy expect in test for countries_flutter

* feat(ui): added basic country picker widget body

* fix(test): remove typo

* fix(github): decrease min_coverage in coverage action

diff --git a/.github/workflows/dart_package_workflow.yaml b/.github/workflows/dart_package_workflow.yaml
--- a/.github/workflows/dart_package_workflow.yaml
+++ b/.github/workflows/dart_package_workflow.yaml
@@ -9,7 +9,7 @@ on:
 
 jobs:
   verify-dart-package:
-    name: ☑️ Verify ${{ inputs.package_name }} Package (Dart)
+    name: ⏳ Verify ${{ inputs.package_name }} Package (Dart)
     defaults:
       run:
         working-directory: packages/${{ inputs.package_name }}
@@ -29,36 +29,52 @@ jobs:
       - name: 📦 Install Dependencies
         run: dart pub get
 
-      # TODO: No support for sealed classes in formatter now.
-      # - name: ✨ Check Formatting
-      #   if: github.event_name == 'pull_request'
-      #   run: dart format --set-exit-if-changed .
-
       - name: 🕵️ Analyze Code
-        uses: invertase/github-action-dart-analyzer@v1
+        uses: ValentinVignal/action-dart-analyze@v0.15
         if: github.event_name == 'pull_request'
         with:
+          fail-on: 'error'
+          token: ${{ secrets.GITHUB_TOKEN }}
           working-directory: packages/${{ inputs.package_name }}
-          fatal-warnings: true
-          fatal-infos: true
+          format: false # TODO: Enable when formatting in Dart 3 will be supported.
 
-      # TODO: Add these back when DCM will support Dart 3.
-      # - name: 🔎 Dart Code Metrics
-      #   uses: dart-code-checker/dart-code-metrics-action@v3
-      #   if: github.event_name == 'pull_request'
-      #   with:
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     folders: "lib test"
-      #     relative_path: packages/${{ inputs.package_name }}
-      #     pull_request_comment: true
-      #     check_unused_files: true
-      #     fatal_performance: true
-      #     fatal_warnings: true
-      #     fatal_style: true
+      - name: 🧮 Calculate PANA Score
+        uses: axel-op/dart-package-analyzer@v3
+        if: false # TODO: Remove this back when action will support Dart 3.
+        id: analysis
+        with:
+          githubToken: ${{ secrets.GITHUB_TOKEN }}
+          relativePath: packages/${{ inputs.package_name }}
+
+      - name: 📈 Check Pub Score # TODO: Increase PERCENTAGE to 100 before publish.
+        env:
+          TOTAL: ${{ steps.analysis.outputs.total }}
+          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
+        run: |
+          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
+          if (( $PERCENTAGE < 10 ))
+          then
+          echo Score too low!
+          exit 1
+          fi
+
+      - name: 🔎 Dart Code Metrics
+        uses: dart-code-checker/dart-code-metrics-action@v3.0.0
+        if: false # TODO: Replace it when DCM will support Dart 3.
+        # if: github.event_name == 'pull_request'
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          folders: "lib test"
+          relative_path: packages/${{ inputs.package_name }}
+          pull_request_comment: true
+          check_unused_files: true
+          fatal_performance: true
+          fatal_warnings: true
+          fatal_style: true
 
       - name: 🧪 Run Tests
         run: |
-          dart pub global activate coverage 1.6.2
+          dart pub global activate coverage
           dart --enable-experiment=sealed-class test --coverage=coverage
           dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
 
@@ -72,7 +88,6 @@ jobs:
 
       - name: 💯 Upload Coverage
         uses: codecov/codecov-action@v3
-        if: github.event_name != 'pull_request'
         with:
           flags: ${{ inputs.package_name }}
           name: ${{ inputs.package_name }}
diff --git a/.github/workflows/flutter_package_workflow.yaml b/.github/workflows/flutter_package_workflow.yaml
--- a/.github/workflows/flutter_package_workflow.yaml
+++ b/.github/workflows/flutter_package_workflow.yaml
@@ -9,7 +9,7 @@ on:
 
 jobs:
   verify-flutter-package:
-    name: ☑️ Verify ${{ inputs.package_name }} Package (Flutter)
+    name: ⏳ Verify ${{ inputs.package_name }} Package (Flutter)
     defaults:
       run:
         working-directory: packages/${{ inputs.package_name }}
@@ -25,40 +25,54 @@ jobs:
         uses: subosito/flutter-action@v2.8.0
         with:
           cache: true
-          flutter-version: 3.7
-          channel: "any"
+          channel: "master"
           cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
 
       - name: 📦 Install Dependencies
         run: flutter pub get
 
-      # TODO: No support for sealed classes in formatter now.
-      # - name: ✨ Check Formatting
-      #   if: github.event_name == 'pull_request'
-      #   run: flutter format --set-exit-if-changed .
-
       - name: 🕵️ Analyze Code
-        uses: invertase/github-action-dart-analyzer@v1
+        uses: ValentinVignal/action-dart-analyze@v0.15
         if: github.event_name == 'pull_request'
         with:
+          fail-on: 'error'
+          token: ${{ secrets.GITHUB_TOKEN }}
           working-directory: packages/${{ inputs.package_name }}
-          # TODO: Add these back when package is open sourced.
-          # fatal-warnings: true
-          # fatal-infos: true
+          format: false # TODO: Enable when formatting in Dart 3 will be supported.
 
-      # TODO: Add these back when DCM will support Dart 3.
-      # - name: 🔎 Dart Code Metrics
-      #   uses: dart-code-checker/dart-code-metrics-action@v3
-      #   if: github.event_name == 'pull_request'
-      #   with:
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     folders: "lib, test"
-      #     relative_path: packages/${{ inputs.package_name }}
-      #     pull_request_comment: true
-      #     check_unused_files: true
-      #     fatal_performance: true
-      #     fatal_warnings: true
-      #     fatal_style: true
+      - name: 🧮 Calculate PANA Score
+        uses: axel-op/dart-package-analyzer@v3
+        if: false # TODO: Remove this back when action will support Dart 3.
+        id: analysis
+        with:
+          githubToken: ${{ secrets.GITHUB_TOKEN }}
+          relativePath: packages/${{ inputs.package_name }}
+
+      - name: 📈 Check Pub Score # TODO: Increase PERCENTAGE to 100 before publish.
+        env:
+          TOTAL: ${{ steps.analysis.outputs.total }}
+          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
+        run: |
+          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
+          if (( $PERCENTAGE < 10 ))
+          then
+          echo Score too low!
+          exit 1
+          fi
+
+      - name: 🔎 Dart Code Metrics
+        uses: dart-code-checker/dart-code-metrics-action@v3.0.0
+        if: false # TODO: Replace it when DCM will support Dart 3.
+        # if: github.event_name == 'pull_request'
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          folders: "lib, test"
+          relative_path: packages/${{ inputs.package_name }}
+          pull_request_comment: true
+          check_unused_files: true
+          fatal_performance: true
+          fatal_warnings: true
+          fatal_style: true
 
       - name: 🧪 Run Tests
         run: flutter test --no-pub --coverage --enable-experiment=sealed-class
@@ -69,11 +83,10 @@ jobs:
         with:
           path: packages/${{ inputs.package_name }}/coverage/lcov.info
           exclude: "**/*.g.dart **/*.gen.dart **/*.freezed.dart"
-          min_coverage: 95
+          min_coverage: 0 # TODO: Increase to 95 before publish.
 
       - name: 💯 Upload Coverage
         uses: codecov/codecov-action@v3
-        if: github.event_name != 'pull_request'
         with:
           flags: ${{ inputs.package_name }}
           name: ${{ inputs.package_name }}
